import type { Metadata } from 'next'
import './globals.css'
import Layout from '@/src/components/layout/Layout'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<Layout children={children} />
			</body>
		</html>
	)
}
